### PR TITLE
Add support for filtering by name

### PR DESCRIPTION
**Pull request by mortenlj**
When testing changes locally, it can be useful to only process the relevant files, avoiding the need to process everything.

This change introduces use of `getopt`, and adds a `--filter` option that takes a glob (passed directly to `find -name`).
It also introduces a change in the "undocumented" 6th option `NO_LABEL`, which is replaced by a option `--no-label`.

### CODE REVIEW

**Comment by mortenlj** [comment]
Av en eller annen grunn går det ikke å requeste review fra github-teamet på denne, og CODEOWNERS ser heller ikke ut til å virke (ikke oppdatert etter flytting til nais-orgen?), så plukker noen tilfeldig utvalgte.

**Review by kimtore — APPROVED** [review]
Good stuff

**Review by jhrv — APPROVED** [review]
Very nice, this has been a TODO since forever 😅 

Maybe also add the new features to the readme. 
Does it make sense to add a testcase for the new features?

**Review by Kyrremann — APPROVED** [review]

**Comment by mortenlj** [comment]
> Maybe also add the new features to the readme.

Forgot about that, done.

> Does it make sense to add a testcase for the new features?

Yup. Done.

**Pull request merged**
